import { type Category } from "../types";

export const CATEGORY_CONFIG: Record<
  Category,
  { role_keywords: string[]; skill_keywords: string[] }
> = {
  "Full Stack Developer": {
    role_keywords: [
      "full stack developer",
      "senior full stack",
      "frontend engineer",
      "backend engineer",
      "software engineer",
    ],
    skill_keywords: [
      "react",
      "node",
      "typescript",
      "python",
      "java",
      "sql",
      "postgresql",
      "mongodb",
      "docker",
      "kubernetes",
      "aws",
      "gcp",
      "azure",
      "rest apis",
      "graphql",
      "next js",
      "redux",
      "django",
      "flask",
    ],
  },
  "Marketing Specialist": {
    role_keywords: [
      "marketing specialist",
      "marketing manager",
      "digital marketing",
      "growth",
      "brand",
      "content",
      "seo",
      "sem",
      "ppc",
      "social media",
    ],
    skill_keywords: [
      "seo",
      "sem",
      "google ads",
      "facebook ads",
      "content",
      "copywriting",
      "email",
      "crm",
      "analytics",
      "ga4",
      "hubspot",
      "marketo",
      "social",
    ],
  },
  Accounting: {
    role_keywords: [
      "accountant",
      "accounting",
      "accounts payable",
      "accounts receivable",
      "financial analyst",
      "bookkeeper",
      "controller",
      "tax",
    ],
    skill_keywords: [
      "accounting",
      "excel",
      "gaap",
      "quickbooks",
      "sap",
      "oracle",
      "financial reporting",
      "reconciliation",
      "tax",
    ],
  },
  "Cybersecurity Analyst": {
    role_keywords: [
      "cybersecurity",
      "security engineer",
      "security analyst",
      "security operations",
      "soc",
      "information security",
      "appsec",
    ],
    skill_keywords: [
      "security",
      "network security",
      "siem",
      "threat",
      "vulnerability",
      "splunk",
      "ids",
      "ips",
      "owasp",
      "incident response",
    ],
  },
  "Data Scientist": {
    role_keywords: [
      "data scientist",
      "ml engineer",
      "machine learning engineer",
      "research scientist",
      "ai engineer",
    ],
    skill_keywords: [
      "python",
      "pandas",
      "numpy",
      "scikit",
      "sklearn",
      "pytorch",
      "tensorflow",
      "sql",
      "nlp",
      "computer vision",
      "statistics",
      "r",
    ],
  },
};

export const TARGET_CATEGORIES: Category[] = [
  "Full Stack Developer",
  "Marketing Specialist",
  "Accounting",
  "Cybersecurity Analyst",
  "Data Scientist",
];

export const DEFAULT_WEIGHTS = { experience: 0.45, skills: 0.35, salary: 0.2 };
